import type { Product } from "@/types";

export const products: Product[] = [
  {
    id: "table-appoint-or",
    name: "Table d'Appoint Royale Dorée",
    category: "meubles-egyptiens",
    origin: "egypt",
    material: "Bois sculpté, feuille d'or, marbre",
    price: 2450,
    images: ["/products/gold-side-table.jpg"],
    description:
      "Table d'appoint ronde au plateau de marbre veiné, portée par un piètement en bois massif richement sculpté et doré à la feuille. Une pièce centrale qui apporte une touche de palais à votre salon.",
    dimensions: "Ø 70 cm × H 65 cm",
    inStock: true,
    featured: true,
    popularity: 95,
    createdAt: "2024-11-02",
  },
  {
    id: "bureau-marqueterie",
    name: "Bureau & Chaises en Marqueterie",
    category: "meubles-egyptiens",
    origin: "egypt",
    material: "Bois précieux, marqueterie, cuir",
    price: 5800,
    images: ["/products/marquetry-desk-chairs.jpg"],
    description:
      "Ensemble bureau et chaises en marqueterie florale fine, assises en cuir véritable. Un travail d'ébénisterie d'exception alliant fonctionnalité et art décoratif.",
    dimensions: "Bureau : L 130 × P 70 × H 78 cm",
    inStock: true,
    featured: true,
    popularity: 88,
    createdAt: "2024-10-18",
  },
  {
    id: "banquette-bordeaux",
    name: "Banquette Capitonnée Bordeaux",
    category: "meubles-turcs",
    origin: "turkey",
    material: "Velours, bois doré sculpté",
    price: 4200,
    images: ["/products/burgundy-gold-settee.jpg"],
    description:
      "Banquette d'apparat en velours bordeaux profond, capitonnage main et structure en bois sculpté doré à la feuille. L'élégance turque dans toute sa splendeur.",
    dimensions: "L 150 × P 70 × H 110 cm",
    inStock: true,
    featured: true,
    popularity: 97,
    createdAt: "2024-11-20",
  },
  {
    id: "salle-manger-or",
    name: "Salle à Manger Dorée Cristal",
    category: "meubles-turcs",
    origin: "turkey",
    material: "Bois doré, verre, tapisserie florale",
    price: 12500,
    images: ["/products/gold-dining-set.jpg"],
    description:
      "Ensemble de salle à manger somptueux : table en verre sur piètement doré sculpté et chaises tapissées de motifs floraux. Pour des réceptions inoubliables.",
    dimensions: "Table : L 240 × P 110 × H 78 cm",
    inStock: true,
    featured: true,
    popularity: 92,
    createdAt: "2024-09-30",
  },
  {
    id: "console-marqueterie",
    name: "Console Bureau en Marqueterie",
    category: "decoration-interieure",
    origin: "egypt",
    material: "Bois de rose, marqueterie, bronze doré",
    price: 6900,
    images: ["/products/marquetry-console-desk.jpg"],
    description:
      "Console-bureau d'exception en marqueterie laquée, ornements en bronze doré et plateau verni. Une pièce maîtresse pour entrée ou bureau de prestige.",
    dimensions: "L 160 × P 60 × H 80 cm",
    inStock: true,
    featured: false,
    popularity: 80,
    createdAt: "2024-08-12",
  },
  {
    id: "vitrine-doree",
    name: "Vitrine d'Exposition Dorée",
    category: "decoration-interieure",
    origin: "turkey",
    material: "Bois doré sculpté, verre, velours",
    price: 8400,
    images: ["/products/gold-display-cabinet.jpg"],
    description:
      "Grande vitrine d'apparat dorée à la feuille, fond velours et verre biseauté. Idéale pour mettre en valeur cristaux et porcelaines précieuses.",
    dimensions: "L 140 × P 45 × H 220 cm",
    inStock: true,
    featured: true,
    popularity: 85,
    createdAt: "2024-10-05",
  },
  {
    id: "balancoire-balcon",
    name: "Balançoire en Rotin de Balcon",
    category: "decoration-exterieure",
    origin: "other",
    material: "Rotin synthétique, coussin déperlant",
    price: 1350,
    images: ["/products/rattan-swing-balcony.jpg"],
    description:
      "Balançoire suspendue en rotin tressé avec coussin moelleux, parfaite pour balcons et terrasses. Confort et style pour vos moments de détente.",
    dimensions: "L 70 × P 70 × H 195 cm",
    inStock: true,
    featured: false,
    popularity: 78,
    createdAt: "2024-11-10",
  },
  {
    id: "balancoire-jardin-grise",
    name: "Balançoire de Jardin Grise",
    category: "decoration-exterieure",
    origin: "other",
    material: "Rotin gris, acier, coussins épais",
    price: 1690,
    images: ["/products/gray-swing-garden.jpg"],
    description:
      "Grande balançoire de jardin en rotin gris avec coussins généreux et structure acier robuste. Le luxe outdoor pour vos espaces verts.",
    dimensions: "L 120 × P 100 × H 200 cm",
    inStock: true,
    featured: false,
    popularity: 74,
    createdAt: "2024-09-22",
  },
  {
    id: "balancoire-ronde",
    name: "Balançoire Ronde en Rotin",
    category: "decoration-exterieure",
    origin: "other",
    material: "Rotin naturel, coussin beige",
    price: 1490,
    images: ["/products/round-rattan-swing.jpg"],
    description:
      "Balançoire ronde enveloppante en rotin tressé, coussin beige profond. Un cocon élégant pour jardin ou véranda.",
    dimensions: "Ø 110 × H 200 cm",
    inStock: false,
    featured: false,
    popularity: 70,
    createdAt: "2024-07-15",
  },
  {
    id: "balancoire-oeuf",
    name: "Balançoire Œuf Suspendue",
    category: "decoration-exterieure",
    origin: "other",
    material: "Rotin clair, coussins crème",
    price: 1550,
    images: ["/products/egg-rattan-swing.jpg"],
    description:
      "Balançoire suspendue en forme d'œuf, rotin clair et coussins crème enveloppants. Confort cocooning pour extérieurs raffinés.",
    dimensions: "L 95 × P 75 × H 195 cm",
    inStock: true,
    featured: false,
    popularity: 72,
    createdAt: "2024-10-28",
  },
  {
    id: "collection-cristal",
    name: "Collection Cristal Taillé",
    category: "cristal",
    origin: "other",
    material: "Cristal au plomb taillé main",
    price: 980,
    images: ["/products/crystal-collection.jpg"],
    description:
      "Ensemble de cristallerie taillée à la main : coupe, bonbonnière et vases aux motifs diamant. La lumière sublimée par le cristal.",
    dimensions: "Coupe : Ø 30 cm",
    inStock: true,
    featured: false,
    popularity: 68,
    createdAt: "2024-11-15",
  },
  {
    id: "collection-porcelaine",
    name: "Collection Porcelaine Dorée",
    category: "porcelaine",
    origin: "other",
    material: "Porcelaine fine, dorure à l'or",
    price: 1120,
    images: ["/products/porcelain-collection.jpg"],
    description:
      "Pièces décoratives en porcelaine peinte main et rehaussée d'or : vases et jarres aux motifs floraux. Art classique pour intérieurs précieux.",
    dimensions: "Vase : H 40 cm",
    inStock: true,
    featured: false,
    popularity: 65,
    createdAt: "2024-08-30",
  },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}
